# Generated by Django 4.2.5 on 2023-09-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Trufa',
        ),
    ]
