# Generated by Django 4.2.5 on 2023-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trufa', '0002_trufa_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trufa',
            old_name='capa',
            new_name='Imagem',
        ),
        migrations.AddField(
            model_name='trufa',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trufa',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
