# Generated by Django 4.2.5 on 2023-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trufa', '0003_rename_capa_trufa_imagem_trufa_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trufa',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
