# Generated by Django 4.2.5 on 2023-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trufa', '0006_categoriaviewset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trufa',
            name='categoria',
        ),
        migrations.AddField(
            model_name='trufa',
            name='sem_lactose',
            field=models.BooleanField(default=False),
        ),
    ]
