# Generated by Django 4.2.5 on 2023-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trufa', '0007_remove_trufa_categoria_trufa_sem_lactose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaSerializer',
        ),
        migrations.DeleteModel(
            name='CategoriaViewSet',
        ),
        migrations.AddField(
            model_name='trufa',
            name='ao_leite',
            field=models.BooleanField(default=False),
        ),
    ]
