# Generated by Django 4.2.7 on 2023-12-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufa', '0009_remove_trufa_ao_leite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trufa',
            name='sem_lactose',
        ),
    ]
